server {
    listen 80;
    
    server_name localhost;

        # Sets the static directory.


        # This tells index.html is the page to serve when hit at / endpoint.


    location / {

        root /usr/share/nginx/html;

        index index.html;
        # The below mentioned line means:
        # 1. $uri : Try to search for urls which access files like -> /styles/main.css
        # 2. $uri/ : Try to map with directories like-> /images/
        # 3. /index.html : If nothing found the route to index.html or the fall back uri.

        try_files $uri $uri/index.html /404.html;
    }
}
