events {}

http {
    server {
        listen 80;

        server_name localhost;

        # Sets the static directory.

        root /usr/share/nginx/html;

        # This tells index.html is the page to serve when hit at / endpoint.

        index index.html;

        location / {

        # The below mentioned line means:
        # 1. $uri : Try to search for urls which access files like -> /styles/main.css
        # 2. $uri/ : Try to map with directories like-> /images/
        # 3. /index.html : If nothing found the route to index.html or the fall back uri.

            try_files $uri $uri/ /index.html;
        }
    }
}
