// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

@com.google.protobuf.Generated
public interface IsUserExistResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.v1.IsUserExistResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exists = 1 [json_name = "exists"];</code>
   * @return The exists.
   */
  boolean getExists();
}
