services:
  # This proxy only need when running the application using docker-compose.
  proxy:
    container_name: nexus-proxy
    image: biswasakash/nexussphere-docker-proxy:latest
    ports:
      - "8000:80"
    networks:
      - proxy-network
    depends_on:
      - client
      - gateway

  client:
    container_name: nexus-client 
    image: biswasakash/nexussphere-client:latest 
    networks:
      - proxy-network

  # Authentication gateway for the services.
  gateway:
    container_name: nexus-gateway
    image: biswasakash/nexussphere-gateway:latest
    networks:
      - service-network
      - proxy-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - users

  users:
    container_name: nexus-users
    image: biswasakash/nexussphere-users:latest
    networks:
      - service-network
      - mongo-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  mongo:
    container_name: nexus-mongo-docker
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=password 
    networks:
      - mongo-network
    # Only to inspect the database.
    ports:
      - "27018:27017"

networks:
  proxy-network:
    driver: bridge
  service-network:
    driver: bridge
  mongo-network:
    driver: bridge
  postgres-network:
    driver: bridge
