// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access-manager/access-manager.proto
// Protobuf Java Version: 4.34.1

package com.nexussphere.common.grpc;

@com.google.protobuf.Generated
public final class AccessManagerProto extends com.google.protobuf.GeneratedFile {
  private AccessManagerProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "AccessManagerProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateSecurityGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateSecurityGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateSecurityGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateSecurityGroupResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#access-manager/access-manager.proto\"V\n" +
      "\032CreateSecurityGroupRequest\022\026\n\006userId\030\001 " +
      "\001(\tR\006userId\022 \n\013workspaceId\030\002 \001(\tR\013worksp" +
      "aceId\";\n\033CreateSecurityGroupResponse\022\034\n\t" +
      "isSucceed\030\001 \001(\010R\tisSucceed2l\n\030AccessMana" +
      "gerGRPCService\022P\n\023CreateSecurityGroup\022\033." +
      "CreateSecurityGroupRequest\032\034.CreateSecur" +
      "ityGroupResponseB3\n\033com.nexussphere.comm" +
      "on.grpcB\022AccessManagerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateSecurityGroupRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_CreateSecurityGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateSecurityGroupRequest_descriptor,
        new java.lang.String[] { "UserId", "WorkspaceId", });
    internal_static_CreateSecurityGroupResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_CreateSecurityGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateSecurityGroupResponse_descriptor,
        new java.lang.String[] { "IsSucceed", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
