// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access-manager/access-manager.proto
// Protobuf Java Version: 4.34.1

package com.nexussphere.common.grpc;

@com.google.protobuf.Generated
public interface CreateSecurityGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSecurityGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string workspaceId = 2 [json_name = "workspaceId"];</code>
   * @return The workspaceId.
   */
  java.lang.String getWorkspaceId();
  /**
   * <code>string workspaceId = 2 [json_name = "workspaceId"];</code>
   * @return The bytes for workspaceId.
   */
  com.google.protobuf.ByteString
      getWorkspaceIdBytes();
}
