// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access-manager/access-manager.proto
// Protobuf Java Version: 4.34.1

package com.nexussphere.common.grpc;

@com.google.protobuf.Generated
public interface CreateSecurityGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSecurityGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSucceed = 1 [json_name = "isSucceed"];</code>
   * @return The isSucceed.
   */
  boolean getIsSucceed();
}
