// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/users.proto
// Protobuf Java Version: 4.34.1

package com.nexussphere.common.grpc;

@com.google.protobuf.Generated
public interface IsUserExistRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IsUserExistRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
