// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/users.proto
// Protobuf Java Version: 4.34.1

package com.nexussphere.common.grpc;

@com.google.protobuf.Generated
public final class UsersProto extends com.google.protobuf.GeneratedFile {
  private UsersProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "UsersProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IsUserExistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IsUserExistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IsUserExistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IsUserExistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024users/v1/users.proto\",\n\022IsUserExistReq" +
      "uest\022\026\n\006userId\030\001 \001(\tR\006userId\"-\n\023IsUserEx" +
      "istResponse\022\026\n\006exists\030\001 \001(\010R\006exists2K\n\017U" +
      "serGRPCService\0228\n\013IsUserExist\022\023.IsUserEx" +
      "istRequest\032\024.IsUserExistResponseB+\n\033com." +
      "nexussphere.common.grpcB\nUsersProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IsUserExistRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_IsUserExistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IsUserExistRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_IsUserExistResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_IsUserExistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IsUserExistResponse_descriptor,
        new java.lang.String[] { "Exists", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
