// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access_manager/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.accessmanager.v1;

@com.google.protobuf.Generated
public final class AccessManager extends com.google.protobuf.GeneratedFile {
  private AccessManager() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "AccessManager");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_access_manager_v1_CreateSecurityGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_access_manager_v1_CreateSecurityGroupResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034access_manager/v1/main.proto\022\021access_m" +
      "anager.v1\"X\n\032CreateSecurityGroupRequest\022" +
      "\027\n\007user_id\030\001 \001(\tR\006userId\022!\n\014workspace_id" +
      "\030\002 \001(\tR\013workspaceId\"<\n\033CreateSecurityGro" +
      "upResponse\022\035\n\nis_succeed\030\001 \001(\010R\tisSuccee" +
      "d2\220\001\n\030AccessManagerGRPCService\022t\n\023Create" +
      "SecurityGroup\022-.access_manager.v1.Create" +
      "SecurityGroupRequest\032..access_manager.v1" +
      ".CreateSecurityGroupResponseBK\n8com.bisw" +
      "asakashdev.nexussphere.protogen.accessma" +
      "nager.v1B\rAccessManagerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_access_manager_v1_CreateSecurityGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor,
        new java.lang.String[] { "UserId", "WorkspaceId", });
    internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_access_manager_v1_CreateSecurityGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor,
        new java.lang.String[] { "IsSucceed", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
