// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access_manager/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.accessmanager.v1;

@com.google.protobuf.Generated
public interface CreateSecurityGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:access_manager.v1.CreateSecurityGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_succeed = 1 [json_name = "isSucceed"];</code>
   * @return The isSucceed.
   */
  boolean getIsSucceed();
}
