// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access_manager/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.accessmanager.v1;

/**
 * Protobuf type {@code access_manager.v1.CreateSecurityGroupResponse}
 */
@com.google.protobuf.Generated
public final class CreateSecurityGroupResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:access_manager.v1.CreateSecurityGroupResponse)
    CreateSecurityGroupResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CreateSecurityGroupResponse");
  }
  // Use CreateSecurityGroupResponse.newBuilder() to construct.
  private CreateSecurityGroupResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateSecurityGroupResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.class, com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.Builder.class);
  }

  public static final int IS_SUCCEED_FIELD_NUMBER = 1;
  private boolean isSucceed_ = false;
  /**
   * <code>bool is_succeed = 1 [json_name = "isSucceed"];</code>
   * @return The isSucceed.
   */
  @java.lang.Override
  public boolean getIsSucceed() {
    return isSucceed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isSucceed_ != false) {
      output.writeBool(1, isSucceed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isSucceed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isSucceed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse)) {
      return super.equals(obj);
    }
    com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse other = (com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse) obj;

    if (getIsSucceed()
        != other.getIsSucceed()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_SUCCEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSucceed());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code access_manager.v1.CreateSecurityGroupResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:access_manager.v1.CreateSecurityGroupResponse)
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.class, com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.Builder.class);
    }

    // Construct using com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isSucceed_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupResponse_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse getDefaultInstanceForType() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse build() {
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse buildPartial() {
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse result = new com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isSucceed_ = isSucceed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse) {
        return mergeFrom((com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse other) {
      if (other == com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse.getDefaultInstance()) return this;
      if (other.getIsSucceed() != false) {
        setIsSucceed(other.getIsSucceed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isSucceed_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isSucceed_ ;
    /**
     * <code>bool is_succeed = 1 [json_name = "isSucceed"];</code>
     * @return The isSucceed.
     */
    @java.lang.Override
    public boolean getIsSucceed() {
      return isSucceed_;
    }
    /**
     * <code>bool is_succeed = 1 [json_name = "isSucceed"];</code>
     * @param value The isSucceed to set.
     * @return This builder for chaining.
     */
    public Builder setIsSucceed(boolean value) {

      isSucceed_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_succeed = 1 [json_name = "isSucceed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSucceed() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isSucceed_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:access_manager.v1.CreateSecurityGroupResponse)
  }

  // @@protoc_insertion_point(class_scope:access_manager.v1.CreateSecurityGroupResponse)
  private static final com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse();
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSecurityGroupResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateSecurityGroupResponse>() {
    @java.lang.Override
    public CreateSecurityGroupResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateSecurityGroupResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSecurityGroupResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

