// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: access_manager/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.accessmanager.v1;

/**
 * Protobuf type {@code access_manager.v1.CreateSecurityGroupRequest}
 */
@com.google.protobuf.Generated
public final class CreateSecurityGroupRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:access_manager.v1.CreateSecurityGroupRequest)
    CreateSecurityGroupRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CreateSecurityGroupRequest");
  }
  // Use CreateSecurityGroupRequest.newBuilder() to construct.
  private CreateSecurityGroupRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateSecurityGroupRequest() {
    userId_ = "";
    workspaceId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.class, com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKSPACE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object workspaceId_ = "";
  /**
   * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
   * @return The workspaceId.
   */
  @java.lang.Override
  public java.lang.String getWorkspaceId() {
    java.lang.Object ref = workspaceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workspaceId_ = s;
      return s;
    }
  }
  /**
   * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
   * @return The bytes for workspaceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkspaceIdBytes() {
    java.lang.Object ref = workspaceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workspaceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, workspaceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, workspaceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest)) {
      return super.equals(obj);
    }
    com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest other = (com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getWorkspaceId()
        .equals(other.getWorkspaceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + WORKSPACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkspaceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code access_manager.v1.CreateSecurityGroupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:access_manager.v1.CreateSecurityGroupRequest)
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.class, com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.Builder.class);
    }

    // Construct using com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      workspaceId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.AccessManager.internal_static_access_manager_v1_CreateSecurityGroupRequest_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest getDefaultInstanceForType() {
      return com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest build() {
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest buildPartial() {
      com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest result = new com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.workspaceId_ = workspaceId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest) {
        return mergeFrom((com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest other) {
      if (other == com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getWorkspaceId().isEmpty()) {
        workspaceId_ = other.workspaceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              workspaceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object workspaceId_ = "";
    /**
     * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
     * @return The workspaceId.
     */
    public java.lang.String getWorkspaceId() {
      java.lang.Object ref = workspaceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workspaceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
     * @return The bytes for workspaceId.
     */
    public com.google.protobuf.ByteString
        getWorkspaceIdBytes() {
      java.lang.Object ref = workspaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workspaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
     * @param value The workspaceId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspaceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      workspaceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkspaceId() {
      workspaceId_ = getDefaultInstance().getWorkspaceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string workspace_id = 2 [json_name = "workspaceId"];</code>
     * @param value The bytes for workspaceId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      workspaceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:access_manager.v1.CreateSecurityGroupRequest)
  }

  // @@protoc_insertion_point(class_scope:access_manager.v1.CreateSecurityGroupRequest)
  private static final com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest();
  }

  public static com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSecurityGroupRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateSecurityGroupRequest>() {
    @java.lang.Override
    public CreateSecurityGroupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateSecurityGroupRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSecurityGroupRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.accessmanager.v1.CreateSecurityGroupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

