name: Users CI pipeline

on:
  push:
    branches: ["main", "dev", "staging"]
    paths:
      - '.github/workflows/users-ci.yaml'
      - 'users/**'
      - 'common-java/**'
      - 'proto-gen-java/**'
  pull_request:
    branches: ["main", "staging"]
    paths:
      - 'users/**'
      - 'common-java/**'
      - 'proto-gen-java/**'
  workflow_dispatch:
    inputs:
      reason:
        description: 'To check some changes that do not trigger the workflow.'
        required: false
        default: 'Manual trigger'
jobs:
  build:
    runs-on: ubuntu-latest
    # Clone the repository.
    steps:
      - name: Setup env
        uses: ./.github/actions/setup-java-env

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./users/Dockerfile
          push: true
          tags: |
            ${{ github.ref_name == 'main' && format('{0}/nexussphere-users:latest', secrets.DOCKER_USERNAME) || '' }}

            ${{ github.ref_name == 'main' && format('{0}/nexussphere-users:{1}', secrets.DOCKER_USERNAME, github.sha) || '' }}

            ${{ github.ref_name != 'main' && format('{0}/nexussphere-users:{1}', secrets.DOCKER_USERNAME, github.ref_name) || '' }}
