// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

/**
 * Protobuf type {@code users.v1.GetUsersResponse}
 */
@com.google.protobuf.Generated
public final class GetUsersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:users.v1.GetUsersResponse)
    GetUsersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetUsersResponse");
  }
  // Use GetUsersResponse.newBuilder() to construct.
  private GetUsersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetUsersResponse() {
    users_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.class, com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> users_;
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(1, users_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = users_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(users_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse)) {
      return super.equals(obj);
    }
    com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse other = (com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse) obj;

    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code users.v1.GetUsersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:users.v1.GetUsersResponse)
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.class, com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.Builder.class);
    }

    // Construct using com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
      } else {
        users_ = null;
        usersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersResponse_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse getDefaultInstanceForType() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse build() {
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse buildPartial() {
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse result = new com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse result) {
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
    }

    private void buildPartial0(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse) {
        return mergeFrom((com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse other) {
      if (other == com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse.getDefaultInstance()) return this;
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto m =
                  input.readMessage(
                      com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.parser(),
                      extensionRegistry);
              if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(m);
              } else {
                usersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        users_ = new java.util.ArrayList<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto>(users_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder> usersBuilder_;

    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder setUsers(
        int index, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder setUsers(
        int index, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        int index, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        int index, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder getUsersBuilder(
        int index) {
      return internalGetUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public java.util.List<? extends com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder addUsersBuilder() {
      return internalGetUsersFieldBuilder().addBuilder(
          com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.getDefaultInstance());
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder addUsersBuilder(
        int index) {
      return internalGetUsersFieldBuilder().addBuilder(
          index, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.getDefaultInstance());
    }
    /**
     * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
     */
    public java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder> 
         getUsersBuilderList() {
      return internalGetUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder> 
        internalGetUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto.Builder, com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder>(
                users_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:users.v1.GetUsersResponse)
  }

  // @@protoc_insertion_point(class_scope:users.v1.GetUsersResponse)
  private static final com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse();
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUsersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUsersResponse>() {
    @java.lang.Override
    public GetUsersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUsersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUsersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

