// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

@com.google.protobuf.Generated
public interface GetUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.v1.GetUsersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @return A list containing the userId.
   */
  java.util.List<java.lang.String>
      getUserIdList();
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @return The count of userId.
   */
  int getUserIdCount();
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @param index The index of the element to return.
   * @return The userId at the given index.
   */
  java.lang.String getUserId(int index);
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the userId at the given index.
   */
  com.google.protobuf.ByteString
      getUserIdBytes(int index);
}
