// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

/**
 * Protobuf type {@code users.v1.GetUsersRequest}
 */
@com.google.protobuf.Generated
public final class GetUsersRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:users.v1.GetUsersRequest)
    GetUsersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetUsersRequest");
  }
  // Use GetUsersRequest.newBuilder() to construct.
  private GetUsersRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetUsersRequest() {
    userId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.class, com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList userId_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @return A list containing the userId.
   */
  public com.google.protobuf.ProtocolStringList
      getUserIdList() {
    return userId_;
  }
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @return The count of userId.
   */
  public int getUserIdCount() {
    return userId_.size();
  }
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @param index The index of the element to return.
   * @return The userId at the given index.
   */
  public java.lang.String getUserId(int index) {
    return userId_.get(index);
  }
  /**
   * <code>repeated string user_id = 1 [json_name = "userId"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the userId at the given index.
   */
  public com.google.protobuf.ByteString
      getUserIdBytes(int index) {
    return userId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userId_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < userId_.size(); i++) {
        dataSize += computeStringSizeNoTag(userId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUserIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest)) {
      return super.equals(obj);
    }
    com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest other = (com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest) obj;

    if (!getUserIdList()
        .equals(other.getUserIdList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserIdCount() > 0) {
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code users.v1.GetUsersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:users.v1.GetUsersRequest)
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.class, com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.Builder.class);
    }

    // Construct using com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.Main.internal_static_users_v1_GetUsersRequest_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest getDefaultInstanceForType() {
      return com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest build() {
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest buildPartial() {
      com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest result = new com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        userId_.makeImmutable();
        result.userId_ = userId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest) {
        return mergeFrom((com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest other) {
      if (other == com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest.getDefaultInstance()) return this;
      if (!other.userId_.isEmpty()) {
        if (userId_.isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
        } else {
          ensureUserIdIsMutable();
          userId_.addAll(other.userId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ensureUserIdIsMutable();
              userId_.add(input.readStringRequireUtf8());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList userId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureUserIdIsMutable() {
      if (!userId_.isModifiable()) {
        userId_ = new com.google.protobuf.LazyStringArrayList(userId_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @return A list containing the userId.
     */
    public com.google.protobuf.ProtocolStringList
        getUserIdList() {
      userId_.makeImmutable();
      return userId_;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @return The count of userId.
     */
    public int getUserIdCount() {
      return userId_.size();
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param index The index of the element to return.
     * @return The userId at the given index.
     */
    public java.lang.String getUserId(int index) {
      return userId_.get(index);
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the userId at the given index.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes(int index) {
      return userId_.getByteString(index);
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param index The index to set the value at.
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUserIdIsMutable();
      userId_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to add.
     * @return This builder for chaining.
     */
    public Builder addUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUserIdIsMutable();
      userId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param values The userId to add.
     * @return This builder for chaining.
     */
    public Builder addAllUserId(
        java.lang.Iterable<java.lang.String> values) {
      ensureUserIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, userId_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string user_id = 1 [json_name = "userId"];</code>
     * @param value The bytes of the userId to add.
     * @return This builder for chaining.
     */
    public Builder addUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureUserIdIsMutable();
      userId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:users.v1.GetUsersRequest)
  }

  // @@protoc_insertion_point(class_scope:users.v1.GetUsersRequest)
  private static final com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest();
  }

  public static com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUsersRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetUsersRequest>() {
    @java.lang.Override
    public GetUsersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUsersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUsersRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.nexussphere.protogen.users.v1.GetUsersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

