// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

@com.google.protobuf.Generated
public interface GetUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.v1.GetUsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  java.util.List<com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto> 
      getUsersList();
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProto getUsers(int index);
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  java.util.List<? extends com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .users.v1.UserDetailesProto users = 1 [json_name = "users"];</code>
   */
  com.biswasakashdev.nexussphere.protogen.users.v1.Types.UserDetailesProtoOrBuilder getUsersOrBuilder(
      int index);
}
