// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

@com.google.protobuf.Generated
public final class Main extends com.google.protobuf.GeneratedFile {
  private Main() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Main");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_IsUserExistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_IsUserExistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_IsUserExistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_IsUserExistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023users/v1/main.proto\022\010users.v1\"-\n\022IsUse" +
      "rExistRequest\022\027\n\007user_id\030\001 \001(\tR\006userId\"-" +
      "\n\023IsUserExistResponse\022\026\n\006exists\030\001 \001(\010R\006e" +
      "xists2]\n\017UserGRPCService\022J\n\013IsUserExist\022" +
      "\034.users.v1.IsUserExistRequest\032\035.users.v1" +
      ".IsUserExistResponseB4\n0com.biswasakashd" +
      "ev.nexussphere.protogen.users.v1P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_users_v1_IsUserExistRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_users_v1_IsUserExistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_IsUserExistRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_users_v1_IsUserExistResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_users_v1_IsUserExistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_IsUserExistResponse_descriptor,
        new java.lang.String[] { "Exists", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
