// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.34.1

package com.biswasakashdev.nexussphere.protogen.users.v1;

@com.google.protobuf.Generated
public final class Main extends com.google.protobuf.GeneratedFile {
  private Main() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Main");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_GetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_GetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_GetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_GetUsersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023users/v1/main.proto\022\010users.v1\032\024users/v" +
      "1/types.proto\"*\n\017GetUsersRequest\022\027\n\007user" +
      "_id\030\001 \003(\tR\006userId\"E\n\020GetUsersResponse\0221\n" +
      "\005users\030\001 \003(\0132\033.users.v1.UserDetailesProt" +
      "oR\005users2T\n\017UserGRPCService\022A\n\010GetUsers\022" +
      "\031.users.v1.GetUsersRequest\032\032.users.v1.Ge" +
      "tUsersResponseB4\n0com.biswasakashdev.nex" +
      "ussphere.protogen.users.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.biswasakashdev.nexussphere.protogen.users.v1.Types.getDescriptor(),
        });
    internal_static_users_v1_GetUsersRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_users_v1_GetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_GetUsersRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_users_v1_GetUsersResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_users_v1_GetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_GetUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    descriptor.resolveAllFeaturesImmutable();
    com.biswasakashdev.nexussphere.protogen.users.v1.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
